server:
  port: ${SERVER_PORT}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**
        - id: training-service
          uri: lb://training-service
          predicates:
            - Path=/api/courses/**, /api/videos/**, /api/categories/**

# Eureka
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, configprops
info:
  app:
    name: "Gateway Service"
    description: "This service handles requests between services"
    version: "1.0.0"
  team:
    name: "SportMentor Team"
    contact: "support@sportmentor.com"
  build:
    artifact: "gateway-service"
    version: "${project.version}"
    time: "${maven.build.timestamp}"