version: '3.8'
name: sportmentor
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    command: ["start-dev"]
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"

#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:23.0.4
#    env_file:
#      - src/main/resources/imports/keycloak.env
#    build:
#      context: ../../..
#      dockerfile: Dockerfile
#    ports:
#      - "8084:8080"
#    healthcheck:
#      test: "curl -f http://localhost:8084/health/ready || exit 1"
#    depends_on:
#      - keycloakdb
#    command: -v start-dev --import-realm --features=account3,declarative-user-profile
#    volumes:
#      - ./src/main/resources/imports:/opt/keycloak/data/import/
#      - ./src/main/resources/imports:/opt/keycloak/providers/
#    networks:
#      - grid-network
#  keycloakdb:
#    container_name: keycloakdb
#    image: postgres:latest
#    env_file:
#      - src/main/resources/imports/keycloak.env
#    networks:
#      - grid-network