server:
  port: ${SERVER_PORT}
spring:
  application:
    name: training-service
#  DB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Eureka
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, configprops

info:
  app:
    name: "Training Service"
    description: "This service handles training information"
    version: "1.0.0"
  team:
    name: "SportMentor Team"
    contact: "support@sportmentor.com"
  build:
    artifact: "training-service"
    version: "${project.version}"
    time: "${maven.build.timestamp}"